#ifndef __NBODY_DEVICE_CL_INCLUDES_H_
#define __NBODY_DEVICE_CL_INCLUDES_H_

#define CL_HPP_MINIMUM_OPENCL_VERSION 120
#define CL_HPP_TARGET_OPENCL_VERSION  120
#define CL_HPP_ENABLE_EXCEPTIONS
#include <CL/cl2.hpp>

#endif

